### ISSUE TITLE
support for python > 2.6

### ISSUE THREAD

**Issue by johnyf** [upverter/schematic-file-converter#200]
Running with `python >= 2.7` says:

`WARNING: RUNNING UNSUPPORTED VERSION OF PYTHON (2.7 > 2.6)`

and changing the code to go past this error, parsing `eagle` fails.
What is the main reason for incompatibility with python 2.7?

**Comment by Patrik356b** [comment]
Can't install and can't copy the error message either on 2.7.12

![crap](http://puu.sh/qPzUJ/3aabfc57d4.png)

**Comment by iwelch82** [comment]
I seem to be able to install successfully on Python 2.7.9 but when I try to run upconverter I'm missing a package. 
```C:\Users\iwelch\Documents>python -m upconvert.upconverter -h
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\python_upconvert-0.8.9-py2.7.egg\upconvert\upconverter.py", line 65, in <module>
    from upconvert.parser import openjson as openjson_p, kicad as kicad_p, geda as geda_p, \
  File "C:\Python27\lib\site-packages\python_upconvert-0.8.9-py2.7.egg\upconvert\parser\openjson.py", line 36, in <module>
    from upconvert.core.layout import Segment, Layer
  File "C:\Python27\lib\site-packages\python_upconvert-0.8.9-py2.7.egg\upconvert\core\layout.py", line 23, in <module>
    import freetype
ImportError: No module named freetype```

When I try to install the module with PIP it's not found

**Comment by jacobjennings** [comment]
brew install freetype
pip install freetype-py
